Repository graphql-nexus/nexus, pull requests merged in 2020-01, with the labels that each got.

#257 improve: log pretty rendering
  src/cli/commands/dev.tsx
  src/framework/app.ts
  src/lib/logger/__snapshots__/main.spec.ts.snap
  src/lib/logger/main.spec.ts
  src/lib/logger/prettifier.ts
  src/utils/logger.ts
Labels: scope/logging, type/enhancement

#276 feat: expose missing pieces of nexus surface api
  src/framework/app.ts
  src/framework/nexus.ts
Labels: type/feature

#281 fix(cli): exit with code returned by command
  README.md
  src/cli/commands/dev.ts
  src/cli/helpers/CLI.ts
  src/cli/index.ts
  src/utils/process.ts
  src/utils/tsc.ts
  src/watcher/watcher.ts
  test/__helpers/utils.ts
  test/__helpers/workspace.ts
  test/integration/__snapshots__/build.spec.ts.snap
  test/integration/build.spec.ts
Labels: bug, scope/builder

#279 feat: allow plugins to have their own listener on the main watcher
  package.json
  src/framework/plugin.ts
  src/utils/console.ts
  src/watcher/chokidar.ts
  src/watcher/watcher.ts
  yarn.lock
Labels: scope/plugins, type/feature

#290 docs: start testing guide
  docs/guides/testing.md
  docs/index.html
  src/cli/index.ts
  src/framework/testing.ts
Labels: type/docs

#299 feat: plugin hook to extend test context
  src/framework/nexus.ts
  src/framework/plugin.ts
  src/framework/testing.ts
Labels: scope/plugins, scope/testing, type/feature

#303 fix: use explicit default from prompts
  src/cli/commands/create/app.ts
  src/cli/commands/create/plugin.ts
  src/framework/plugin.ts
  tsconfig.json
Labels: bug

#305 fix: EPIPE error when server is restarted several times
  src/watcher/chokidar.ts
  src/watcher/runner.ts
  src/watcher/watcher.ts
Labels: type/bug

#306 docs: refine bug issue template
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/other.md
Labels: type/docs

#317 improve: show url in server start msg
  src/framework/app.ts
Labels: polish, type/enhancement

#318 improve: plugin module path and interface
  .github/semantic.yml
  plugin.d.ts
  plugin.js
  src/cli/commands/build.ts
  src/cli/commands/create/app.ts
  src/cli/commands/create/plugin.ts
  src/cli/commands/dev.ts
  src/cli/commands/generate.ts
  src/core/plugin/index.ts
  src/framework/app.ts
  src/framework/testing.ts
  src/plugin.ts
  src/testing.ts
  src/utils/db-driver.ts
  src/watcher/types.ts
  testing.d.ts
  testing.js
Labels: note/breaking-change, type/improve

#320 feat: allow plugins to register backing types
  src/core/plugin/index.ts
  src/framework/app.ts
Labels: impact/high, type/feature

#322 feat(logger): permit level config via LOG_LEVEL
  src/framework/app.ts
  src/lib/logger/index.spec.ts
  src/lib/logger/level.ts
  src/lib/logger/root-logger.ts
Labels: scope/logger, type/feature

#327 improve: remove apollo server
  docs/references/components.md
  package.json
  src/framework/app.ts
  src/framework/server.ts
  src/framework/testing.ts
  yarn.lock
Labels: scope/server, type/improve

#335 feat(logger): settings namespace
  docs/references/api.md
  src/lib/logger/index.spec.ts
  src/lib/logger/root-logger.ts
Labels: note/breaking-change, type/feature

#338 fix(testing): TestContextCore for internal
  src/core/plugin/index.ts
  src/framework/testing.ts
  src/lib/utils/index.ts
Labels: type/bug

#341 feat(logger): pretty mode color control
  src/lib/logger/__snapshots__/index.spec.ts.snap
  src/lib/logger/index.spec.ts
  src/lib/logger/pino.ts
  src/lib/logger/root-logger.ts
  src/lib/utils/index.ts
Labels: scope/logger, type/feature

#344 feat: app.schema namespace
  docs/getting-started/tutorial.md
  docs/references/api.md
  src/cli/commands/create/app.ts
  src/framework/app.ts
  test/integration/build.spec.ts
  test/integration/prisma/build.spec.ts
Labels: note/breaking-change, type/feature

#346 feat(schema): relay connections
  docs/references/api.md
  src/core/plugin/index.ts
  src/framework/app.ts
  src/framework/layout.ts
  src/framework/schema/index.ts
  src/framework/schema/logger.ts
  src/framework/schema/modules.ts
  src/framework/schema/nexus.ts
  src/framework/schema/schema.ts
  src/framework/start.ts
  src/lib/utils/index.ts
  test/__helpers/run.ts
Labels: type/feature

#351 improve(logger): format context
  docs/references/api.md
  src/lib/logger/__snapshots__/index.spec.ts.snap
  src/lib/logger/demo.ts
  src/lib/logger/index.spec.ts
  src/lib/logger/prettifier.ts
Labels: scope/logger, type/improve
